// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH0HyRQB5_Q20akaYDJgkkgWrJmeKCKkQ',
    appId: '1:861555391577:web:6a4bb196e4df9d97b90548',
    messagingSenderId: '861555391577',
    projectId: 'upivenue',
    authDomain: 'upivenue.firebaseapp.com',
    storageBucket: 'upivenue.firebasestorage.app',
    measurementId: 'G-D8E40N363Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAazaEW7sPlgT_gHj4GyyAZuLSHpZi9E8',
    appId: '1:861555391577:android:d78bdddd4416353bb90548',
    messagingSenderId: '861555391577',
    projectId: 'upivenue',
    storageBucket: 'upivenue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMP1skd17wlhdFtQPPphrMNAR0QGdysQ',
    appId: '1:861555391577:ios:bf9072385779627eb90548',
    messagingSenderId: '861555391577',
    projectId: 'upivenue',
    storageBucket: 'upivenue.firebasestorage.app',
    iosBundleId: 'com.example.venueupi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMP1skd17wlhdFtQPPphrMNAR0QGdysQ',
    appId: '1:861555391577:ios:bf9072385779627eb90548',
    messagingSenderId: '861555391577',
    projectId: 'upivenue',
    storageBucket: 'upivenue.firebasestorage.app',
    iosBundleId: 'com.example.venueupi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH0HyRQB5_Q20akaYDJgkkgWrJmeKCKkQ',
    appId: '1:861555391577:web:9febe312faee2708b90548',
    messagingSenderId: '861555391577',
    projectId: 'upivenue',
    authDomain: 'upivenue.firebaseapp.com',
    storageBucket: 'upivenue.firebasestorage.app',
    measurementId: 'G-LDWGH943WQ',
  );
}
